import type { Metadata } from "next";
import { SeoLanding, type SeoLandingData } from "../../ui/seo-landing";

const pages:Record<string,{title:string;description:string;data:SeoLandingData}>={
 beauty:{title:"美妆个护出海社媒与 WhatsApp 获客方案",description:"面向美妆个护外贸厂家的海外社媒内容、私标询盘接待与销售跟进方案。",data:{eyebrow:"BEAUTY & PERSONAL CARE",title:"让客户看懂成分、肤感和私标能力，再进入有效询盘",definition:"灵枢 AI 美妆个护方案帮助出口厂家围绕成分、肤感、使用场景、包装定制与打样流程生产海外内容，并在 WhatsApp 询盘中补齐市场、渠道、MOQ、标签语言和样品需求。",audience:"护肤、彩妆、洗护、香氛和个人护理产品的 OEM、ODM 与出口厂家",outcomes:[["内容重点","成分教育、使用演示、包装定制和生产能力。"],["询盘问题","市场、渠道、MOQ、标签语言、配方与样品。"],["人工边界","功效承诺、法规、认证与最终报价由人工核实。"]],questions:[["美妆厂家海外社媒应该发什么？","优先展示产品使用、肤感、成分逻辑、包装选择、打样和生产流程，而不是只重复目录参数。"],["AI 如何判断私标客户是否值得跟进？","通过目标市场、销售渠道、预计数量、包装要求、标签语言和时间计划逐步补齐采购信号。"],["医疗或功效表述如何处理？","未获审核的功效、法规和认证内容不应自动生成或发送，应进入人工核实。"]],next:{href:"/demo?intent=trial",label:"用美妆产品资料体验"}}},
 healthcare:{title:"医药健康产品出海社媒方案",description:"面向医药健康产品出口企业的专业内容、合规边界和 WhatsApp 询盘接待方案。",data:{eyebrow:"HEALTHCARE EXPORT",title:"专业内容可以被看见，功效与法规边界必须被守住",definition:"灵枢 AI 医药健康方案基于已审核的产品、生产和质量资料生成教育型海外内容；涉及医疗功效、认证、适用人群和市场法规的问题固定进入人工核实。",audience:"医疗器械、健康产品、营养品及相关供应链出口企业",outcomes:[["专业内容","产品教育、生产流程、质量控制与使用说明。"],["知识边界","只调用企业已审核资料，缺少依据时明确暂停。"],["合规接管","功效、认证、法规和敏感人群问题转人工。"]],questions:[["AI 可以回答医疗功效问题吗？","只有企业审核并允许使用的知识才可用于回复；无法确认的功效问题必须转人工。"],["内容如何避免夸大？","生成时限定知识来源和禁用表述，并在发布前保留人工审核。"],["不同国家法规是否自动判断？","不能把模型输出当作法律结论，具体市场法规应由企业合规人员或专业顾问确认。"]],next:{href:"/demo?intent=trial",label:"体验受控内容与接待"}}},
 "building-materials":{title:"建材出口社媒与工程询盘方案",description:"面向建材出口厂家的工程内容、规格询盘和 WhatsApp 销售跟进方案。",data:{eyebrow:"BUILDING MATERIALS",title:"用工程场景证明产品，再把规格问题交给正确的人",definition:"灵枢 AI 建材方案帮助出口厂家围绕性能对比、工程场景、安装过程、供应能力与质量控制生产内容，并在询盘中确认规格、标准、数量、包装、目的港和期望交期。",audience:"饰面材料、门窗、五金、卫浴、石材及工程建材出口厂家",outcomes:[["内容重点","工程案例、性能对比、安装过程与生产供应。"],["询盘问题","规格、标准、数量、包装、港口和交期。"],["销售接管","定制方案、项目报价与交付承诺进入人工。"]],questions:[["建材产品适合拍什么内容？","优先展示安装过程、工程效果、性能测试、结构细节、包装和装柜等可验证信息。"],["AI 能否直接做工程报价？","不建议。项目报价涉及规格、数量、贸易条款和交付条件，应在补齐信息后转交销售。"],["如何追踪客户来自哪个案例？","内容发布记录与 WhatsApp 入口关联后，可以保留来源平台和具体内容上下文。"]],next:{href:"/demo?intent=trial",label:"用建材资料体验"}}}
};
export function generateStaticParams(){return Object.keys(pages).map(slug=>({slug}));}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const {slug}=await params;const p=pages[slug];return p?{title:p.title,description:p.description,alternates:{canonical:`/solutions/${slug}`}}:{};}
export default async function Page({params}:{params:Promise<{slug:string}>}){const {slug}=await params;return <SeoLanding data={(pages[slug]??pages.beauty).data}/>;}
