import type { Metadata } from "next";
import { CustomerTimelineDemo, ProductStudioDemo, PublishingCalendarDemo, WhatsappHandoffDemo } from "../../ui/product-demos";
import { SeoLanding, type SeoLandingData } from "../../ui/seo-landing";

const pages: Record<string,{meta:string;description:string;data:SeoLandingData}> = {
 "content-studio":{meta:"AI 海外社媒内容工作台",description:"把外贸产品资料转成多语言脚本、分镜、配音和短视频。",data:{eyebrow:"AI CONTENT STUDIO",title:"把产品资料变成海外内容",definition:"灵枢 AI 内容工作台帮助外贸厂家基于产品资料、目标市场和企业知识生成海外社媒脚本、分镜、配音、封面与短视频，并将成片继续送入发布排期。",audience:"缺少稳定海外内容团队，或内容生产依赖多人反复协作的外贸厂家",outcomes:[["理解产品","调用已审核的产品、卖点和企业知识。"],["生成成片","选择生成模式、素材、声音、配乐与封面。"],["继续发布","成片直接进入多账号排期，而不是停在下载文件。"]],questions:[["可以直接使用工厂现有图片和视频吗？","可以。素材库可承接产品图、工厂视频和已有内容，再用于脚本与成片生成。"],["是否支持多语言内容？","产品流程面向海外市场设计，可根据目标市场生成和调整不同语言表达。"],["生成内容会不会虚构产品能力？","内容应以企业知识和已审核资料为依据；医药功效、认证等高风险表述需要人工核实。"]],next:{href:"/product/social-publishing",label:"查看多平台发布"}}},
 "social-publishing":{meta:"海外社媒多平台发布",description:"统一管理 TikTok、Facebook、Instagram Reels 和 YouTube 内容排期。",data:{eyebrow:"SOCIAL PUBLISHING",title:"一处排期，发布多个平台",definition:"灵枢 AI 多平台发布功能帮助外贸团队统一管理 TikTok、Facebook、Instagram Reels 与 YouTube 的账号连接、内容排期和发布状态，并为后续 WhatsApp 询盘保留内容来源。",audience:"需要运营多个海外平台、账号或市场的外贸营销团队",outcomes:[["统一排期","在一个日历中查看内容与账号计划。"],["平台适配","按不同平台调整内容表达和发布信息。"],["来源追踪","为进入 WhatsApp 的客户保留平台与内容上下文。"]],questions:[["当前支持哪些发布平台？","当前正式产品已实现 TikTok、Facebook、Instagram Reels 与 YouTube 的账号连接和视频发布。"],["LinkedIn 可以直接发布吗？","LinkedIn 直接发布目前暂未开放，不应在销售材料中表述为已支持。"],["平台授权失败怎么办？","平台接入受客户账号状态、应用审核和授权权限影响，开通时由顾问协助检查。"]],next:{href:"/product/whatsapp-ai",label:"查看 WhatsApp AI"}}},
 "whatsapp-ai":{meta:"WhatsApp AI 询盘接待",description:"使用企业知识自动接待、补齐采购信息并按风险转人工。",data:{eyebrow:"WHATSAPP AI",title:"先接住询盘，再交给销售",definition:"灵枢 AI 将社媒内容来源、客户语言、产品和历史对话带入 WhatsApp 接待上下文，帮助企业快速回答标准问题、补齐采购信息、判断风险并在关键节点转交人工。",audience:"受时差、语言和首响速度影响，容易错过海外询盘的外贸销售团队",outcomes:[["即时首响","基于企业知识处理低风险标准问题。"],["采购分级","补齐市场、数量、规格、时间与合作意向。"],["安全转人工","价格、条款、大单与风险问题暂停自动回复。"]],questions:[["AI 可以自动报价吗？","是否自动回复由企业配置；报价通常应设为草稿确认或人工处理。"],["AI 不知道答案时会怎样？","连续知识缺口、客户明确要求人工或高风险问题会触发转人工。"],["销售接管后还能看到前文吗？","可以。客户来源、对话摘要、意向证据和建议动作会一起保留。"]],next:{href:"/product/lead-management",label:"查看客户与销售跟进"}}},
 "lead-management":{meta:"外贸询盘与销售跟进",description:"集中查看客户来源、采购信号、AI 摘要与下一步销售动作。",data:{eyebrow:"LEAD MANAGEMENT",title:"让销售先跟重点客户",definition:"灵枢 AI 客户工作台将内容来源、历史对话、采购信号、风险原因和建议动作放入同一时间线，帮助销售优先处理高价值机会并完成连续跟进。",audience:"询盘分散在个人 WhatsApp、客户背景不清晰或跟进依赖个人记忆的销售团队",outcomes:[["来源可见","知道客户来自哪个平台、账号和内容。"],["证据分级","查看数量、预算、时间和合作意向等原始证据。"],["连续跟进","AI 与人工动作保留记录，减少上下文丢失。"]],questions:[["BANT 分级会不会凭空判断？","不应该。判断应关联客户原话、来源和历史动作，缺少信息时明确标记未知。"],["人工接管会中断客户体验吗？","接管时保留完整上下文，销售不需要要求客户重复说明。"],["能否直接归因到订单？","内容和询盘来源已有追踪基础；订单级归因仍需结合企业实际 CRM 与订单流程配置。"]],next:{href:"/solutions/beauty",label:"查看行业解决方案"}}}
};
export function generateStaticParams(){return Object.keys(pages).map(slug=>({slug}));}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const {slug}=await params;const p=pages[slug];return p?{title:p.meta,description:p.description,alternates:{canonical:`/product/${slug}`}}:{};}
export default async function Page({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const p=pages[slug]??pages["content-studio"];const demos={"content-studio":<ProductStudioDemo/>,"social-publishing":<PublishingCalendarDemo/>,"whatsapp-ai":<WhatsappHandoffDemo/>,"lead-management":<CustomerTimelineDemo/>};return <SeoLanding data={p.data} media={demos[slug as keyof typeof demos]??demos["content-studio"]}/>;}
